# frozen_string_literal: true

puts 'all functions'
require 'funcky/a_array/join'
require 'funcky/a_array/join_post'
require 'funcky/a_array/join_pre'
require 'funcky/a_comparison/and'
require 'funcky/a_comparison/default'
require 'funcky/a_comparison/eq'
require 'funcky/a_comparison/gt'
require 'funcky/a_comparison/gte'
require 'funcky/a_comparison/lt'
require 'funcky/a_comparison/lte'
require 'funcky/a_comparison/ne'
require 'funcky/a_comparison/or'
require 'funcky/a_inflection/ordinal'
require 'funcky/a_inflection/ordinalize'
require 'funcky/a_inflection/pluralize'
require 'funcky/a_inflection/pluralize_by_number'
require 'funcky/a_transform/backslash'
require 'funcky/a_transform/camel'
require 'funcky/a_transform/constant'
require 'funcky/a_transform/dash'
require 'funcky/a_transform/dot'
require 'funcky/a_transform/double_colon'
require 'funcky/a_transform/lamel'
require 'funcky/a_transform/lower'
require 'funcky/a_transform/proper'
require 'funcky/a_transform/sentence'
require 'funcky/a_transform/slash'
require 'funcky/a_transform/snake'
require 'funcky/a_transform/title'
require 'funcky/a_transform/upper'
